name: 'Validate KFP Compiled Files'
description: 'Validates if the changed Kubeflow Pipelines .py files were compiled'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  pipelines-map-file:
    description: 'The file with the mapping from .py to .yaml'
    required: true
  requirements-file:
    description: 'The requirements.txt file'
    required: true
  compile-args:
    description: 'Extra arguments to pass to kfp dsl compile (optional)'
    required: false
  modified-only:
    description: 'Only validate entries whose files are Git-modified'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      shell: bash
      run: pip install -r "${{ inputs.requirements-file }}"

    - name: Verify compiled pipelines
      shell: bash
      run: python "${{ github.action_path }}/verify_kfp_compiled.py" --map-file "${{ inputs.pipelines-map-file }}" --compile-args "${{ inputs.compile-args || '' }}" ${{ inputs.modified-only == 'true' && '--modified-only' || '' }}
